### ISSUE TITLE
Simply removing a "/*" will not let a rule work.

### ISSUE THREAD

**Issue by MarkRH** [stonecrusher/simpleMenuWizard#1]
Trying this out and discovered that the CSS will not work unless the last item of a rule does not end in a comma.  To make editing the files easier, you could put a dummy selector as the last item:

      /* image-context.css */
      
      /* #context-reloadimage,			/* Reload Image */
      /* #context-viewimage,				/* View Image */
      /* #context-copyimage-contents,		/* Copy Image */
      /* #context-copyimage,				/* Copy Image Location */
      /* #context-sep-copyimage,			/******* Separator *******/
      /* #context-saveimage,				/* Save Image As... */
       #context-sendimage,				/* Email Image... */
       #context-setDesktopBackground,	/* Set As Desktop Background... */
      /* #context-viewimageinfo,			/* View Image Info */
      /* #inspect-separator,				/******* Separator *******/
      /* #context-inspect,				/* Inspect Element (Q) */
      /* #context-contentAreaContextMenu > menuseparator:nth-child(92), /** Separator **/
      /* #ublock0_raymondhill_net_uBlock0-blockElement	/* Block element (by uBlock addon) */
       #dummy
      	{ display:none !important; }

**Comment by stonecrusher** [comment]
> unless the last item of a rule does not end in a comma

Uhm, that's in the [Readme](https://github.com/stonecrusher/simpleMenuWizard/blob/master/README.md).

But good idea with the dummy, I'll change it.

**Comment by MarkRH** [comment]
You're right, that is mentioned in the Readme. My bad. Sorry.

Although, I ended up just putting what I wanted directly into my userChrome.css and will use this as reference material.  Thanks for all the work putting this together.

**Comment by stonecrusher** [comment]
Thanks for the hint, should be ok now.

* Added dummy items
* removed line from readme
* corrected alignment (was a problem with my editor)
