### ISSUE TITLE
Can't remove the navigation bar from context menu FF 59.0.2 

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [stonecrusher/simpleMenuWizard#10]
Hi, I'm trying to remove the whole navigation bar with icons from the right click context menu, but for some reason i can't get it to work. If i uncomment the first line nothing happens, tried uncommenting each line separately, still no results. What am i missing here? How would the working config look like?

**Comment by stonecrusher** [comment]
Works well here on `59.0.2`. Did you stick to the instructions?
Make sure you restart the browser after changes.

![before_after](https://user-images.githubusercontent.com/1388389/38991793-1effc28a-43df-11e8-9567-9b25aaac0e7f.png)
![sc](https://user-images.githubusercontent.com/1388389/38991792-1ee429e4-43df-11e8-9028-e2b270d6a116.png)

**Comment by Vulgaris-Viridis** [comment]
You are right, my bad sorry. I extracted the content into the wrong "chrome" folder from this path "[...]\storage\permanent\**chrome**.

Thanks for your prompt reply!
