### ISSUE TITLE
Hide "Reopen in container" in tab context menu item.

### ISSUE THREAD

**Issue by cleisson** [stonecrusher/simpleMenuWizard#11]
This new item introduced in the nightly version of the browser can be hidden including the following line in tab-context.css file:

#tabContextMenu #context_reopenInContainer,

**Comment by stonecrusher** [comment]
Thanks for the info!
I'll leave this open and add it when it hits beta status. Doesn't even have a translation yet.

**Comment by stonecrusher** [comment]
https://github.com/stonecrusher/simpleMenuWizard/commit/69e2dd4370c3a0f370712864ccad587c7ea39d72
