### ISSUE TITLE
can't hide take a screenshot in firefox 61

### ISSUE THREAD

**Issue by ladygh** [stonecrusher/simpleMenuWizard#12]
/*** blank-context.css ***/

/*#screenshots_mozilla_org_create-screenshot,  /* Take a Screenshot                    */

this setting doesn't work

**Comment by stonecrusher** [comment]
The identifiers changed and a separator was added.

Try this:

```
/* #context-inspect + menuseparator:not([id]),           /* ********* Separator (FF61+) **********/
/* #screenshots_mozilla_org-menuitem-_create-screenshot, /* Take a Screenshot (FF61+)            */
```

**Comment by ladygh** [comment]
Not working

**Comment by stonecrusher** [comment]
Just checked again, it is working.

Did you remove the `/*` at line start?  
Did you restart the browser?

**Comment by ladygh** [comment]
It works now, sorry I didn't fully restart.
Many thanks!

**Comment by stonecrusher** [comment]
https://github.com/stonecrusher/simpleMenuWizard/commit/69e2dd4370c3a0f370712864ccad587c7ea39d72
