### ISSUE TITLE
An Extra Separator 

### ISSUE THREAD

**Issue by farshad007** [stonecrusher/simpleMenuWizard#16]
Hi
Thanks for this great project.
There is just one minor issue I noticed:
in line 26 of blank-context.css, the word "context" is repeated twice which would create a double Separator.
[/* #context-context-sep-viewsource,                      /************** Separator ***************/](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/blank-context.css)
I just don't guess it was meant to be like that.

Cheers
Farshad

**Comment by stonecrusher** [comment]
Hey,
yep, it seems to be a copy-paste typo.
I even remember some selectors having typos from Firefox itself, but they might be corrected over time.
Thanks for the hint!
