### ISSUE TITLE
uBlock does not disappear

### ISSUE THREAD

**Issue by Wombat2018** [stonecrusher/simpleMenuWizard#17]
I removed '/*' at the beginning of the line '@import url("./simpleMenuWizard/opt_uBO.css");', but uBlock is still everywhere.
Everything else is working, e.g. I deleted some of my installed addons from the context menu and some entries from link-context.css, select-context.css and tab-context.css.

Is it necessary to do something else?

**Comment by stonecrusher** [comment]
Thanks for the hint. Your approach was correct.
The identifier used by uBlock has changed. I fixed it in the [new file](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/opt_uBO.css).
