### ISSUE TITLE
Problem when 'hiding all inactive' is enabled

### ISSUE THREAD

**Issue by grosenberg** [stonecrusher/simpleMenuWizard#2]
Firefox 58.0.1 64bit

Everything works as advertised so long as the 'Hide all inactive menu items' option remains disabled.

If the existing 'Hide all inactive menu items' is enabled, however, all subsequent imports are effectively ignored.  Moving the option after all of the imports is a work around.

**Comment by stonecrusher** [comment]
Thank you for reporting. You are right.
@imports [must not stand after rulesets](https://www.w3.org/TR/REC-CSS2/syndata.html#at-rules) if they should work.

Fixed in  https://github.com/stonecrusher/simpleMenuWizard/commit/257f6f757b537005641c929492b4b2f21eca07e9
