### ISSUE TITLE
New entries in tab context menu

### ISSUE THREAD

**Issue by Wombat2018** [stonecrusher/simpleMenuWizard#20]
Hi,

there are some new entries and separators in the tab context menu which are not in your tab-context.css, e.g. context_moveTabOptions.

**Comment by Wombat2018** [comment]
Sorry, my mistake. There are only 2 separators missing in your tab-context.css which are displayed in my tab context menu.

**Comment by stonecrusher** [comment]
Hi,
no problem. I just checked the tab-context.css again and [updated it for FF67](https://github.com/stonecrusher/simpleMenuWizard/commit/0ea4ae41abeacc7fe3635db19c074864884238be).
There are still two separators, none missing, though. One separator selector changed. So I guess it's from a customization on your side? A screenshot could help.

**Comment by Wombat2018** [comment]
Sorry, I looked into it. It was from a customization on my side.
