### ISSUE TITLE
Drop down menus

### ISSUE THREAD

**Issue by Candlemass** [stonecrusher/simpleMenuWizard#22]
There used to be legacy extensions called "Menu Filter" https://addons.thunderbird.net/en-us/firefox/addon/menu-filter/reviews/801081 and "Menu Wizard" http://forums.mozillazine.org/viewtopic.php?f=48&t=2828771 that did exactly this but also had the ability to remove items from all of the drop down menus as well. Sadly they have both been depricated with version 57+ without rewrites.

Is it possible to extend the same functionality you have here for firefox context menus to all of the drop down menus as well?

Cheers and keep up the great work.

**Comment by stonecrusher** [comment]
> Sadly they have both been depricated with version 57+ without rewrites.

Addons simply don't have the permission anymore to change these parts of the UI. So a rewrite is impossible.

Could you specify (screenshot) what you mean by "the dropdown menus"? Quite likely you're talking about the [main menubar](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/main-menubar.css) or the [main hamburger](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/main-hamburger.css)?

> Cheers and keep up the great work.

Thanks! We're all on the same boat :-)

**Comment by Candlemass** [comment]
Indeed those are the ones. Haven't had much time to mess around with this yet but will be doing so on the weekend.

Could you also extend this to remove all the unnecessary junk in the bookmarks menu as well?

Thanks again.

**Comment by stonecrusher** [comment]
You mean [this](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/sidebar-context.css)? :laughing:
