### ISSUE TITLE
Missing items?

### ISSUE THREAD

**Issue by Candlemass** [stonecrusher/simpleMenuWizard#23]
Hello,

In the bookmarks dropdown menu I did not see any CSS code to remove the items from the following image:

https://i.postimg.cc/ZnBfpJ1q/Bookmarks.jpg

Is it possible for these to be added?

Cheers.

**Comment by stonecrusher** [comment]
Hi,
thanks for your report.

> In the bookmarks dropdown menu

Hm, can you help me where that is? Where do I have to click to see that menu? Btw simpleMenuWizard usually is adjusted to the latest stable release which is 68.0.1 at the moment.

> how to remove just the "Ctrl+Shift+A" part of the Add-ons entry

Try this in userChrome.css:
```
#appMenu-addons-button.subviewbutton[shortcut]::after {
  content: ''
}
```

**Comment by Candlemass** [comment]
> 
> 
> Hi,
> thanks for your report.
> 
> > In the bookmarks dropdown menu
> 
> Hm, can you help me where that is? Where do I have to click to see that menu? Btw simpleMenuWizard usually is adjusted to the latest stable release which is 68.0.1 at the moment.
> 
> > how to remove just the "Ctrl+Shift+A" part of the Add-ons entry
> 
> Try this in userChrome.css:
> 
> ```
> #appMenu-addons-button.subviewbutton[shortcut]::after {
>   content: ''
> }
> ```
I believe it's on the right side of the url bar by default, otherwise you should be able to click the "customize" button and drag the icon there from the options available.

I have managed to remove all of the text with the following:

#BMB_viewBookmarksSidebar,
#BMB_bookmarksShowAllTop,
#BMB_bookmarksShowAllTop + menuseparator,
#BMB_bookmarksToolbar,
#BMB_unsortedBookmarks,
#BMB_bookmarksShowAll .menu-accel-container {display:none!important;}   <--- leaves the "Show all bookmarks" button at the bottom of the list for access to that useful menu but removes the unsightly "Ctrl+Shift+B" text from beside it.

However there are still two separator lines that I'm not able to figure out how to remove that were above and below the "Mozilla Firefox" button that you can remove by simply right clicking and hitting "delete".

https://i.postimg.cc/KYTX6kxm/Bookmarks-Menu.jpg




Regarding the hamburger menu, I also tried your provided code in my userChrome.css file but it had no effect.

**Comment by Candlemass** [comment]
The botton line ended up being a hidden mobile item but I did finally get it removed.

Final stack looks as follows to remove everything:

#BMB_viewBookmarksSidebar,
#BMB_bookmarksShowAllTop,
#BMB_bookmarksShowAllTop + menuseparator,
#BMB_bookmarksToolbar,
#BMB_unsortedBookmarks,
#BMB_bookmarksShowAll .menu-accel-container,
#BMB_mobileBookmarks + menuseparator {display:none!important;}

You can use this if you choose to update your project for others that may be interested in modifying their bookmarks drodown if they would rather save the screen realestate and utilize that rather then a toolbar.


I'm still trying to figure out the "Ctrl+Shift+A" issue in the hamburger menu while still keeping the useful "Add-ons" button though.

**Comment by stonecrusher** [comment]
> I'm still trying to figure out the "Ctrl+Shift+A" issue in the hamburger menu while still keeping the useful "Add-ons" button though.

add an `!important` to my suggestion and it works

**Comment by stonecrusher** [comment]
> you should be able to click the "customize" button and drag the icon there from the options available.

Ah now I see. Unfortunately all that stuff from the addons-bar is out of scope at the moment. I would need to include all the other possible default "addons" items which is like a whole new chapter.

> You can use this if you choose to update your project for others that may be interested in modifying their bookmarks dropdown menu if they would rather save the screen realestate and utilize this feature rather then the toolbar.

Thank you! I'm not including it now but definitely relate to that if someone asks.

**Comment by Candlemass** [comment]
No problem. just figured I would report back with the solution. Not everyone likes the dishovelled appearance of toolbars :)

Your update also worked.

Cheers.
