### ISSUE TITLE
Image context menu "#context-sep-copyimage," is incorrect

### ISSUE THREAD

**Issue by Candlemass** [stonecrusher/simpleMenuWizard#24]
Hello,

The "#context-sep-copyimage," is incorrect for the separator in the image context menu.

I have applied it and the separator is still present:

https://i.postimg.cc/Z5X8Xp9w/Image-Context.jpg

Cheers.

**Comment by stonecrusher** [comment]
Cannot reproduce, it works as intended.
![2019-07-21_15-56-28 Win7x32](https://user-images.githubusercontent.com/1388389/61592191-37400300-abd0-11e9-98fe-8ff08a6bd971.png)

**Comment by Candlemass** [comment]
I tried again on some other images and for whatever reason this appears to be exclusive to that specific image on Startpage for some reason. Very odd...

**Comment by stonecrusher** [comment]
If you can give me the link I can investigate a bit further for fun.

**Comment by stonecrusher** [comment]
You removed a lot of stuff. Are you sure it's a separator from the image-context?
The startpage.com image is also a link, so maybe you have a leftover separator from the link-context?

**Comment by Candlemass** [comment]
> 
> 
> You removed a lot of stuff. Are you sure it's a separator from the image-context?
> The startpage.com image is also a link, so maybe you have a leftover separator from the link-context?

I literally copied and pasted the entire stack for the link entry and just double checked and everything is present. I did notice that there are some double entries from menu to menu with the code to remove being the same though. I think I removed them all but not 100% sure. Either way, I don't think that should be the cause.
