### ISSUE TITLE
Help contect menu "Troubleshooting Information" and "Submit feedback" entries are incorrect

### ISSUE THREAD

**Issue by Candlemass** [stonecrusher/simpleMenuWizard#25]
Hello,

The "#menu_troubleShooting" and "#menu_feedbackPage" entries have been applied with no change indicating that they are incorrect.

https://i.postimg.cc/CKFhh6f5/Help-Menu.jpg

Cheers.

**Comment by stonecrusher** [comment]
[IDs changed](https://github.com/stonecrusher/simpleMenuWizard/commit/15c020d1ad715fcd15c6d71c6854e95a19e6476f) in some update, thanks for noticing!

**Comment by Candlemass** [comment]
No problem.

Just tried the updates and they work.

Glad it;s resolved.
