### ISSUE TITLE
Missed Images context menu item

### ISSUE THREAD

**Issue by Candlemass** [stonecrusher/simpleMenuWizard#26]
Hi,

As seen in the following image, I came upon a "This Frame" asset when right clicking an image and I could not find it in any of the providedd CSS files.

https://i.postimg.cc/MK7XzBrs/This-Frame.jpg

**Comment by stonecrusher** [comment]
That image was embedded in an iframe.

See [this](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/frame-context.css) for hiding stuff.

**Comment by Candlemass** [comment]
"#frame"

That took care of it.

Thanks for pointing me in the right direction.
