### ISSUE TITLE
Additional context menu items in gifycat videos that the media entrie does not address

### ISSUE THREAD

**Issue by Candlemass** [stonecrusher/simpleMenuWizard#27]
Hi,

The following extra items are present in "gifycat" videos and There does not appear to be any entries to remove them:

https://i.postimg.cc/5yTD19RM/Media.jpg

Thanks.

**Comment by stonecrusher** [comment]
These seem new.
Added stuff in [1.20](https://github.com/stonecrusher/simpleMenuWizard/commit/64b21ff2f358905607ef3b1b8e02bb57cf875163)
