### ISSUE TITLE
Close Sidebar Button not hiding

### ISSUE THREAD

**Issue by farshad007** [stonecrusher/simpleMenuWizard#28]
Hi!
Thanks for keeping up this great project.
I just wonder if there is something wrong with line 17 in sidebar-header.css, as I cannot get Close Sidebar Button removed/hidden in my FF 72.0.2 (64-bit).

Cheers,
Farshad

**Comment by stonecrusher** [comment]
Hey Farshad,
thank you too for reporting.
You're right, there were some errors (came from a PR long ago - structure might have changed by Mozilla in the meantime).
I gave it [an update](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/sidebar-header.css) and it should work again!
Have a good day!

**Comment by farshad007** [comment]
Hi
Thanks for the quick update.
Although I meant the "Close Sidebar" BUTTON with the 'close-icon', next to the 'sidebar-switcher-arrow' in the 'sidebar-header', not the last TAB in 'sidebarMenu-popup'.
I ll attach a screenshot...
Cheers!
<a href="https://ibb.co/CBQc7JS"><img src="https://i.ibb.co/CBQc7JS/Capture.png" alt="Capture" border="0"></a>

**Comment by stonecrusher** [comment]
Ah I see, screenshot helps.
It feels a bit out of scope for the project but I gave it another [update](https://github.com/stonecrusher/simpleMenuWizard/commit/121fc038bb2f23110e876a38d380532a8ddafd72) anyway.
```
#sidebar-close { display: none !important; }
```
