### ISSUE TITLE
How-to hide screenshoot only on select context menu?

### ISSUE THREAD

**Issue by tmpm697** [stonecrusher/simpleMenuWizard#29]
Currently we can only hide screenshoot on all via `#screenshots_mozilla_org-menuitem-_create-screenshot`, is there away to hide for a specific context menu, like select?

**Comment by stonecrusher** [comment]
Try if this works for you:
```
#context-viewpartialsource-selection:not([hidden]) ~ #screenshots_mozilla_org-menuitem-_create-screenshot {
    display: none !important;
    }
```
The concept of my workaround is to select another item that is only present in the target context and then select the (hopefully following) element to hide.

**Comment by tmpm697** [comment]
that's worked, thanks.
