### ISSUE TITLE
Hiding 'Synced Tabs' option on sidebar menu

### ISSUE THREAD

**Issue by mazesy** [stonecrusher/simpleMenuWizard#3]
Hi,

I'm using this helpful and so well carried out _simpleMenuWizard_ (latest 1.3) together with Aris-t2' 
_Custom CSS_ and _Custom Scrollbar_ .

I'm wondering if there's a Firefox 57+ menu item simpleMenuWizard could handle.
Firefox _Show Sidebars_ toolbar button displays the sidebar on which there is a button to trigger a drop-down list which includes natively _Bookmarks_, _History_, _**Synced Tabs**_.

I'd wish to hide this _Synced Tabs_ option since I don't use Firefox Sync.

Thanks for your work @stonecrusher

**Comment by stonecrusher** [comment]
Hi,
thank you for your feedback.
I agree in the way to change the given option `hide all send to device items` to something for users who don't use sync at all as I don't see much sense in hiding the one but not the other.

Try version 1.5 (you need only the new `userChrome.css` and new `opt_noSync.css`) and enable option `/* @import url("./simpleMenuWizard/opt_noSync.css");` in `userChrome.css` by removing the `/*`.

I renamed `opt_send-to-device-hide-all.css` to `opt_noSync.css`. So you can delete the obsolete `opt_send-to-device-hide-all.css`.

That should solve your issue.
Have a nice weekend,
stonecrusher

**Comment by mazesy** [comment]
_simpleMenuWizard 1.5_ -> `opt_noSync.css` does it!
Many thanks, @stonecrusher . I had read that thread on Reddit and that's where I got the link to your GitHub page. So easier, everything perfectly well explained. A pleasure.
