### ISSUE TITLE
How-to remove "Add to Dictionary" when "Check Spelling" enabled?

### ISSUE THREAD

**Issue by tmpm697** [stonecrusher/simpleMenuWizard#30]
I can't find how-to this, is there a way?

**Comment by stonecrusher** [comment]
Thanks for the report.

Where/When does this pop up? It might be missing, didn't find that yet.

Only thing I know is "Add Dictionaries..." which can be found [here](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/input-context.css#L21).

**Comment by tmpm697** [comment]
Steps to produce:
1. open firefox, open a page that has a box that allow user to input from keyboard.
2. type somthing
3. select a word, right click on that word, select "Check Spelling"
4. you'll see "Add to Dictionary"

see this [picture](https://i.imgur.com/dq6yfkc.png)

**Comment by stonecrusher** [comment]
I could reproduce. Those items were missing in simpleMenuWizard.
Fixed in [v1.26](https://github.com/stonecrusher/simpleMenuWizard/commit/db91a51a2cdb83c8a7c51d5c3791131d39a3d900)
