### ISSUE TITLE
Remove #context-sep-navigation, doesn't work properly?

### ISSUE THREAD

**Issue by tmpm697** [stonecrusher/simpleMenuWizard#31]
I have these settings in my `blank-content.css`:
```
#context-navigation,
#context-sep-navigation,
#context-pocket,
#leave_this_dummy_here
    { display:none !important; }
```
I expect when I click right mouse I won't see first `----` delimitor of `Save Page As...`

expected behavior:
```
Save Page As...
----------------------    <- bottom delimiter 
```

current behavior:
```
----------------------
Save Page As...
----------------------
```

**Comment by stonecrusher** [comment]
Cannot reproduce. Using your code it looks as expected here:
![2020-03-28_19-00-36 Win7x32 (Sicherungspunkt 1)  wird ausgeführt  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/1388389/77830227-675c8000-7127-11ea-8c71-8ef60a6f4eeb.png)
So the separator comes from somewhere else. I suspect either another addon or something like Pocket or the clicked place wasn't blank space but an iframe or picture or something.
Can you reproduce in a fresh profile?

**Comment by tmpm697** [comment]
So how to correctly remove first delimiter as:
```
----------------------   <- remove this
Save Page As...
----------------------
```

**Comment by stonecrusher** [comment]
Can you reproduce in a fresh profile? I can't!
```
#context-sep-navigation { display: none !important; }
```
works as it should and removes the first separator as seen in my screenshot. Firefox 74.0

**Comment by tmpm697** [comment]
I think the first delimiter seems to be default somehow:
![image](https://i.imgur.com/TTwROwF.png)

Same result as your picture, it does not has a delimiter but a line to separate something.

But if you look at the last line "Take a Screenshot", it does not has a delimeter at bottom that I expect same as "Save Page As", is it possible?:
```
Take a Sreenshot
----------------------   <- no bottom line here, unlike "Save Page As"

**Comment by stonecrusher** [comment]
Maybe it's a border from the dark theme you're using?
In my screenshot there is only the default window border. Same at the bottom.
![2020-03-28_21-36-33 Win7x32 (Sicherungspunkt 1)  wird ausgeführt  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/1388389/77833264-510cef00-713c-11ea-80e0-acc83593b93c.png)

In your style, does that line also appear if you do *not* hide the navigation which is on top at default?

**Comment by tmpm697** [comment]
Yes, it always appears either or not I have `#context-sep-navigation,`

**Comment by stonecrusher** [comment]
Well, then it's a styling issue and not a problem of this repository.
You might ask the guys at https://reddit.com/r/FirefoxCSS/ for help with the border-top.
