### ISSUE TITLE
Hide the whole 'This Frame' in frame-context.css

### ISSUE THREAD

**Issue by tmpm697** [stonecrusher/simpleMenuWizard#32]
We have `#context-navigation,` to `Hide whole navigation bar`. Can you add option to `Hide the whole 'This Frame'` in `frame-context.css`?

`#frame,` seems not remove `whole` `'This Frame'` for me.

**Comment by stonecrusher** [comment]
If I understand you correctly, `#frame` should already do what you want (and indeed does in my recent test).
The question is, where are leftovers for you?

**Comment by tmpm697** [comment]
Yes, seem I need to restart firefox to get it applied.

**Comment by stonecrusher** [comment]
Doesn't only seem like it. It's mandatory.
See item 7 in the [instructions](https://github.com/stonecrusher/simpleMenuWizard/blob/master/README.md).
