### ISSUE TITLE
Problem with loading settings

### ISSUE THREAD

**Issue by StrangerInStrangeLand** [stonecrusher/simpleMenuWizard#33]
I recently re-installed my windows and Firefox. Then I copied my settings as before but nothing was changed. I googled and found out that I have to change the setting of firefox to get it loaded in recent version of FF.
I changed "kit.legacyUserProfileCustomizations.stylesheets" in "about:config" to True and it worked as before. Maybe you'd better mention in the the description page.

Source : https://www.youtube.com/watch?v=J0NDzs9PsIg , comment from a user named Grillo

**Comment by stonecrusher** [comment]
It's already in the instructions [for almost a year](https://github.com/stonecrusher/simpleMenuWizard/commit/17950b89558deaf0323dd0f872b63984bfdd8622#diff-04c6e90faac2675aa89e2176d2eec7d8) (see item 6).

But the deep link doesn't work anymore (you now need to separately go to about:config and then actively search for it). I will change it later to make it clear.

**Comment by stonecrusher** [comment]
Ok looked into it. Deeplink was already removed. So no change from my side.

BTW you only had to do this manually again because you reinstalled. If you just upgrade, FF automatically detects if you have `userContent.css` or `userChrome.css` and sets the value to True.
