### ISSUE TITLE
Struggling to remove specific separator in Context Menu through blank-context.css

### ISSUE THREAD

**Issue by Illern69** [stonecrusher/simpleMenuWizard#34]
I'm trying out simpleMenuWizard, but I'm having a minor issue.

When I edit **blank-context.css**, I managed to easily remove all but one of the separators in my Context Menu by following your documented instructions. But when I try to remove the last separator that appears under **Inspect Element (Q)** I fail to hide it. I assume I'm supposed to remove the _/*_ in front of **#context-inspect + menuseparator:not([id]),** but doing so does not successfully hide the separator.

I doubt my old **userChrome.css** interferes with the context menu, and I'm unsure how to remove the final separator. Do you have any ideas?

![context menu](https://user-images.githubusercontent.com/66305099/90428948-109b1700-e0c5-11ea-87b2-872108efb783.png)

![blank-context](https://user-images.githubusercontent.com/66305099/90428940-10028080-e0c5-11ea-8659-4c8a275a3095.png)

![userChrome](https://user-images.githubusercontent.com/66305099/90428949-1133ad80-e0c5-11ea-8082-bf062a8ac35d.png)

**Comment by stonecrusher** [comment]
Hey, thanks for the detailed request.
You're right. Something changed. Please try
```
#context-inspect ~ menuseparator:not([id]),
```
instead of the one with a `+` in the middle.

**Comment by Illern69** [comment]
That worked like a charm! 
Thanks for the help and the speedy reply.

**Comment by stonecrusher** [comment]
Well it's not a perfect solution as it will remove more "unclassified" separators that might follow.
But considering the current one didn't work at all and Mozilla might change stuff again down there, it's a reasonable approach.
Changed it [in the repo](https://github.com/stonecrusher/simpleMenuWizard/commit/21bf9a13839eab87a0ebd62e9a92d310ff9064be).
