### ISSUE TITLE
Just wanted to thank you

### ISSUE THREAD

**Issue by bonelifer** [stonecrusher/simpleMenuWizard#36]
Thanks, this helped me track down items I wasn't able to find before. Now if I could only figure out how to hide, "Show sidebars" and "View history, saved bookmarks, and more" toolbar icons.

**Comment by stonecrusher** [comment]
Thank you for the kind words.
You closed the issue - so you already figured out?
In the main hamburger menu click on "Customize". Afterwards you can just drag and drop the toolbar icons.

**Comment by bonelifer** [comment]
Yeah, I figured it out after I closed it.  I'm a bit strange, as I have my Firefox setup most legacy style. Though I have moved the bookmarks the same line as FILE...HELP line, otherwise  not much different. So finding all these userChrome recipes has really helped me clean out the cruft I don't want. Like I was constantly getting the browser Snapshot dialog popping up when clicking on a link to open it in a tab.
