### ISSUE TITLE
FF broke url and tab bars

### ISSUE THREAD

**Issue by shrek-gabe-itch** [stonecrusher/simpleMenuWizard#37]
Nothing changes when i edit this items:

- [ ] tab-context.css
- [ ] toolbar-context.css
- [ ] urlbar-context.css
- [ ] urlbar-pageaction.css

version 80.0.1 release

**Comment by stonecrusher** [comment]
Cannot reproduce, still works fine.
Did you make sure to follow step 6 and 7 from the instructions?

**Comment by shrek-gabe-itch** [comment]
> Did you make sure to follow step 6 and 7 from the instructions?

Sure
I was able to edit all menus except these
I try disable other modifications and delete startup cache 
nothing changes
![image](https://user-images.githubusercontent.com/58945139/92323966-74768700-f056-11ea-8af8-e0215eb9a686.png)
![image](https://user-images.githubusercontent.com/58945139/92323963-63c61100-f056-11ea-9492-a928526e9668.png)
![image](https://user-images.githubusercontent.com/58945139/92323973-8d7f3800-f056-11ea-9817-228d6ea737c7.png)

**Comment by shrek-gabe-itch** [comment]
I found what the problem is, sublime text incorrectly commented out one line before import these files
