### ISSUE TITLE
context menu print selection and inspect accessibility properties

### ISSUE THREAD

**Issue by ahmedtds** [stonecrusher/simpleMenuWizard#39]
do you know ids of these?
![image](https://user-images.githubusercontent.com/6431737/102689232-81864300-420d-11eb-929d-c92952e3e582.png)

**Comment by stonecrusher** [comment]
Thanks for the notice, I gave it an [update](https://github.com/stonecrusher/simpleMenuWizard/commit/10e190f6adfe71ff1b00cc5175282fc12eb6fca0).

See the selectors you need in the [select-context.css](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/select-context.css).

**Comment by ahmedtds** [comment]
@stonecrusher thanks a lot for print selection.

I still can't find "Inspect Accessibility Properties", I don't want to remove "Inspect Element (Q)", just wanna remove "Inspect Accessibility Properties", do you know about it?

**Comment by stonecrusher** [comment]
Whoops, you're right, I was a bit fast. It's another new selector.
`#context-inspect-a11y`
Gave it another [update](https://github.com/stonecrusher/simpleMenuWizard/commit/a95cc8c49d9af6c0230ae861a119c4ae2176b6d2).
