### ISSUE TITLE
remove "check spelling" and "fill login"

### ISSUE THREAD

**Issue by grand-lotus-iroh** [stonecrusher/simpleMenuWizard#4]
I did not have any luck finding the ID. 
https://github.com/Aris-t2/CustomCSSforFx#how-to-use-custom-user-styles

---

How can I remove from input field the "Check spelling" and "Fill login"?

I don't use sync, and have it disabled in the options. I was hoping that would remove context menu item but it doesn't.

![image](https://user-images.githubusercontent.com/1291364/36421709-9cbf2aea-1607-11e8-8a03-a673611bcc01.png)

**Comment by grand-lotus-iroh** [comment]
i added this code (input-context.css) to get results:

```
/* menuitem[label="Check Spelling"], 			   /* Check Spelling  */
#spell-check-enabled, 
#spell-separator,

#context-sep-paste,
#fill-login-separator,
#fill-login,
```

**Comment by grand-lotus-iroh** [comment]
oOOo dude, you will not believe how buggy / troublesome it was finding that stuff. I musta spent like 45 minutes hunting down the ID's.

You know... now sure about the sync thing either. I don't use it and have it disabled. I was still seeing it but with that `#fill-login,` it's gone.

Thanks for updating the code.

**Comment by stonecrusher** [comment]
> dude, you will not believe how buggy / troublesome it was finding that stuff. 

Oh, I do. Had to learn that once by myself. Now it's much easier :-)
