### ISSUE TITLE
changes to the image context menu

### ISSUE THREAD

**Issue by anonymous-user** [stonecrusher/simpleMenuWizard#40]
I was noticing a double set of separators in my context menu and so I found that Firefox had some changes in its image context menu. For example "View Image Info" no longer seems to exist. #context-sep-copyimage also does not exist but there is now a #context-sep-setbackground. Also the order of the items has changed some.

I attached a copy of the new image-context.css (renamed to txt).

[image-context.txt](https://github.com/stonecrusher/simpleMenuWizard/files/6292264/image-context.txt)

**Comment by stonecrusher** [comment]
Thanks for the notice, it's [fixed](https://github.com/stonecrusher/simpleMenuWizard/commit/77c482d447be3df01dbff43bdc616509d3f3ea80) now.
