### ISSUE TITLE
'New Tab' in tab context menu, at the top

### ISSUE THREAD

**Issue by Ma-ve** [stonecrusher/simpleMenuWizard#41]
There's a new context menu item, in Firefox Nightly ~89.0a1 (2021-04-16):

![image](https://user-images.githubusercontent.com/11227996/115116598-a8c20680-9f9a-11eb-9f8a-cab720ba0d42.png)

**Comment by stonecrusher** [comment]
Thank you. As it's still in alpha, I'll leave this open.
Knowing Mozilla, there probably will be more changes needed.
Scope of this repo is the current is always the current stable release.

**Comment by Ma-ve** [comment]
Ah, righto, apologies!

**Comment by stonecrusher** [comment]
Updated: https://github.com/stonecrusher/simpleMenuWizard/commit/fb8bf9ff7bf11fe86618388daa54a86ea60b7232
