### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by TheGlex** [stonecrusher/simpleMenuWizard#44]
can you deactivate this somehow?
But I think that's a feature of Firefox 

![1](https://user-images.githubusercontent.com/84012336/117792324-76c75b80-b24b-11eb-869d-2f0ce818c0fa.jpg)

**Comment by TheGlex** [comment]
"#screenshots_mozilla_org-menuitem-_create-screenshot /* Take a Screenshot */ { display: none !important; }
(see blank-context.css)" - > is active and does nothing

So there is only what remains to be done 
https://github.com/stonecrusher/simpleMenuWizard#hide-pocket--sync--screenshots

**Comment by stonecrusher** [comment]
Ah, new selector. Try `#context-take-screenshot` instead of `#screenshots_mozilla_org-menuitem-_create-screenshot`

**Comment by stonecrusher** [comment]
There are more changes (e.g. the following separator) and more will come with FF89. Then I need to do quite a big overhaul of the project. So maybe take the selector I gave you for FF88 and then just wait for FF89...

**Comment by TheGlex** [comment]
"Then I need to do quite a big overhaul of the project"
Please don't worry about me.

"Ah, new selector. Try #context-take-screenshot instead of #screenshots_mozilla_org-menuitem-_create-screenshot"
it does not work 
![1](https://user-images.githubusercontent.com/84012336/117953566-6cbe5f00-b316-11eb-9782-40b4113cebda.jpg)

This method works, so I'll take this one
https://github.com/stonecrusher/simpleMenuWizard#hide-pocket--sync--screenshots
