### ISSUE TITLE
Firefox Addon

### ISSUE THREAD

**Issue by TheGlex** [stonecrusher/simpleMenuWizard#45]
Hello

Maybe you can help me.

it's about the add-on clippings
https://addons.mozilla.org/en-US/firefox/addon/clippings/

The context menu cannot be switched off in the add-on.

Is there a possibility via simpleMenuWizard?

![3](https://user-images.githubusercontent.com/84012336/118659300-7865c600-b7ed-11eb-9b33-ae397d144b42.jpg)

**Comment by stonecrusher** [comment]
Try

    menu#_91aa5abe-9de4-4347-b7b5-322c38dd9271_-menuitem-2 {
        display: none !important;
    }

and if it doesn't work, try

    menu[label="Clippings"] {
        display: none !important;
    }

**Comment by TheGlex** [comment]
"menu[label="Clippings"] {
    display: none !important;
}"

it works

Thx

**Comment by TheGlex** [comment]
@stonecrusher
Maybe you can help again

it's about the add-on LastPass
https://addons.mozilla.org/de/firefox/addon/lastpass-password-manager/

The context menu cannot be switched off in the add-on.
![1](https://user-images.githubusercontent.com/84012336/127639498-9d95f93d-bc3f-4907-9063-c225d205d114.jpg)

**Comment by stonecrusher** [comment]
Without looking at it, did you try

   menu[label="LastPass"] {
        display: none !important;
    }

?
xD

**Comment by TheGlex** [comment]
userChrome.css
![1](https://user-images.githubusercontent.com/84012336/127641886-def9d2a5-5c0d-4440-9e28-ae61894bd6b8.jpg)

put it in here like clippings
it doesn't work

**Comment by stonecrusher** [comment]
It is correct what you did. Now I looked it up, this should work:

    #support_lastpass_com-menuitem-1 {
        display: none !important;
    }

However, if that doesn't work, this more generic approach should work (note it's `menuitem`, not `menu`):

```
menu[label="LastPass"] {
    display: none !important;
}
```

**Comment by TheGlex** [comment]
```
#support_lastpass_com-menuitem-1 {
    display: none !important;
}
```
Thanks again, it works
