### ISSUE TITLE
Restore Previous Session

### ISSUE THREAD

**Issue by ahmedtds** [stonecrusher/simpleMenuWizard#46]
`#appMenuRestoreSession,                                /* Restore Previous Session      */`

I can't remove this button anymore, did something change in Firefox regarding it? Maybe its name changed? dunno, can you help please?

**Comment by stonecrusher** [comment]
In FF 89.0 it's definitely `#appMenuRestoreSession`, I just checked again.
You probably use an older version where it is `#appMenuRestoreLastSession`.

**Comment by ahmedtds** [comment]
Well, I'm using latest stable which is 88.0.1 and _appMenuRestoreLastSession_ worked, thanks!

**Comment by stonecrusher** [comment]
Yes I was some days early for FF89 because it's a bigger redesign and I wanted to give people the chance to fix their customizations before release.
