### ISSUE TITLE
"Share" selector in tab context menu?

### ISSUE THREAD

**Issue by e-t-l** [stonecrusher/simpleMenuWizard#48]
With the update to Firefox 89, I've noticed a new menuitem, "Share," in the context menu when you right click on a tab. I couldn't find anything about it searching google, the FirefoxCSS subreddit, or in the FF source code at [https://searchfox.org/mozilla-release/source/browser/base/content/browser.xhtml](https://searchfox.org/mozilla-release/source/browser/base/content/browser.xhtml). Do you have any idea what the CSS selector for this is? I'd really like to be able to hide it.

**Comment by axeltrinidade** [comment]
It's a windows added menu item. Follow https://endurtech.com/remove-share-from-windows-10-context-menu/ to disable it.

**Comment by e-t-l** [comment]
@axeltrinidade I followed the directions and restarted my computer, but it's still there. To be clear, we're talking about this share context menu item in the Firefox 89 tab right-click menu:

![image](https://user-images.githubusercontent.com/40775958/121225425-0840e200-c879-11eb-82b7-05dd5026dbe6.png)

**Comment by axeltrinidade** [comment]
Yes, the same 'Share' menu item.

Try to verify and see if the share option appears in the right click menu of other windows items like .jpg or .pdf?
