### ISSUE TITLE
remove "OneTab" from context menu

### ISSUE THREAD

**Issue by grand-lotus-iroh** [stonecrusher/simpleMenuWizard#5]
I don't see anything in the options, I was hoping maybe you had some wisdom to share. Might you know how I can disable the "OneTab" from the (R) click context menu?

![image](https://user-images.githubusercontent.com/1291364/36421805-e4182964-1607-11e8-9de1-b76681d70fc2.png)

**Comment by grand-lotus-iroh** [comment]
i added this code to my simpleMenuWizard css file

`#extension_one-tab_com_2,`

**Comment by stonecrusher** [comment]
Extension support besides *uBlock Origin* is not planned as there are too many out there.
You can still ask here if you can't inspect it by yourself.

Maybe a separate file just for removing stuff coming from extensions independent from context may be a good idea. I'll see if more people consider that useful. I have no idea how many of the top extensions add stuff to the context menu.

Now that you say it, I think I'll outsource the uBlock thing to an option.

**Comment by grand-lotus-iroh** [comment]
OOOoo... alright that's a smart idea. If you make a master thread or ticket with requests i'll help find and hunt down other people's IDs. I would imagine like you said, there are probably tens of thousands of context menu. The one dude's screen shot on [/r/FirefoxCSS/top/](https://www.reddit.com/r/FirefoxCSS/top/) had like 50 context menu - it was crazy.

GLHF
