### ISSUE TITLE
Duplicate context entry for link-context and search-context

### ISSUE THREAD

**Issue by derickso** [stonecrusher/simpleMenuWizard#50]
Both link-context.css and search-context.css contain the same entry for

#context-searchselect,                  /* Search [Google] for "[selected]" */

which when enabled disables the 'Search [Google] for "[selected]" from both right click on selected text, and right click on links. There should be a way to toggle each one individually if they are contained within separate sheets

**Comment by derickso** [comment]
Yes, I would like to disable searching google on links but not on selected text. I'm not sure what the time constraints are to implementing this stuff but it didn't seem very involved, I would think it would be prudent to separate options whenever possible assuming it's possible. If there isn't sufficient time I could probably write a PR myself if pointed in the right direction

**Comment by stonecrusher** [comment]
Try this:

    #context-copylink[hidden="true"] ~ #context-searchselect

**Comment by stonecrusher** [comment]
Did it work?

**Comment by derickso** [comment]
I tried adding it to link-context.css and it removed 'Search with Google' from a selection source but not link source.

**Comment by stonecrusher** [comment]
And what about `#context-copylink[hidden="false"] ~ #context-searchselect` ?

**Comment by derickso** [comment]
No effect

**Comment by stonecrusher** [comment]
Ok had another look.
I was wrong because it contains double-negative logic. This one works:

    #context-print-selection[hidden="true"] ~ #context-searchselect,

**Comment by derickso** [comment]
Yes it does, thanks
