### ISSUE TITLE
Thanks a lot.

### ISSUE THREAD

**Issue by oklokl** [stonecrusher/simpleMenuWizard#51]
I had a hard time finding this program.
I wanted to edit the menu.
Thank you so much.
:)

**Comment by stonecrusher** [comment]
It's not even a program, but only a guide with documented selector names. However I'm very happy it could help you fix and optimize those strange default menus :-)

This project is linked on a ceratin reddit thread which often is one of the first search results. Furthermore it's in the [CustomCSSforFx](https://github.com/Aris-t2/CustomCSSforFx/issues/2) project which was always my No1 for customizing the UI.
