### ISSUE TITLE
request to remove 'open all in tabs' 

### ISSUE THREAD

**Issue by Marvinoo** [stonecrusher/simpleMenuWizard#54]
![image](https://user-images.githubusercontent.com/45720537/126048036-736ee04a-8024-414f-bbe8-635bb79fc0db.png)

That item is there at the bottom when I click on a bookmarks folder, please allow removing this item together with the separate above it. THANK U

**Comment by stonecrusher** [comment]
Does

    #placesContext_openContainer\:tabs,            /* Open All in Tabs (folder)        */
    #placesContext_openSeparator,                  /************ Separator *************/
        { display: none !important; }

from
https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/sidebar-context.css
not work?
I didn't test it but had a quick look and it still looks good.

**Comment by Marvinoo** [comment]
The mentioned IDs are only working on bookmarks and folder from the Sidebar not the Bookmarks bar. Here > 

![image](https://user-images.githubusercontent.com/45720537/126050207-f0c967e3-fb5b-460f-ab43-4b556538a25e.png)

The ones I'm referring to are in the bookmarks bar's folders and their IDs are : 

`openintabs-menuitem`
`bookmarks-actions-menuseparator`

**Comment by stonecrusher** [comment]
I'm sorry, I can't find it. I made a folder in the bookmarks bar just below the url bar but the selectors are the same as I posted before.

What FF version do you use? Are you talking about the library window? That's currently out of scope, but not necessarily anymore next weekend ;-)

**Comment by Marvinoo** [comment]
> I'm sorry, I can't find it. I made a folder in the bookmarks bar just below the url bar but the selectors are the same as I posted before.

Weird! 

> What FF version do you use? Are you talking about the library window? That's currently out of scope, but not necessarily anymore next weekend ;-)

I'm using 91.0b3

It just shows at the bottom under all the bookmarks in the folders from the Bookmarks Bar.

![image](https://user-images.githubusercontent.com/45720537/126061933-1203a7f4-c381-4298-a132-e3d39b97d023.png)

But I'm gonna try to get rid of them myself using those selectors, if done, I'll close this issue. And happy rocky weekend dude :-))

**Comment by Marvinoo** [comment]
.openintabs-menuitem, .bookmarks-actions-menuseparator, {
    display: none !important;
}
