### ISSUE TITLE
Frame screenshot

### ISSUE THREAD

**Issue by Neurotoxin001** [stonecrusher/simpleMenuWizard#55]
Can't find how to hide "Take screenshot" in frame. For example:
https://www.w3schools.com/html/html_iframe.asp

![изображение](https://user-images.githubusercontent.com/39812401/135152284-68dd96ad-8eea-410b-b4c4-e7eca1efea54.png)

**Comment by Neurotoxin001** [comment]
Also this in tab-context.css is not working:
```
#tabContextMenu #context_sendTabToDevice,                  /* Send Tab to Device      */
#tabContextMenu #context_shareTabURL,                      /* Share tab URL via 3rd party app */
```

I still have "share" button:
![изображение](https://user-images.githubusercontent.com/39812401/135162778-e47623b7-d57c-472c-aef9-cddf797750f2.png)

Firefox 92.0.1

**Comment by stonecrusher** [comment]
Thanks for the report. Probably the selectors changed or I simply forgot the new sub-menu.
I will look into it on saturday.

**Comment by stonecrusher** [comment]
"Take Screenshot" is new for frame contextmenu. I added it.
https://github.com/stonecrusher/simpleMenuWizard/commit/329dab5bd92b7545cda9b7a766a89a33ed33786c
```
/* #context-take-frame-screenshot,          /* Take Screenshot          */
/* #context-take-frame-screenshot
                       + menuseparator,     /******** Separator *********/
```

**Comment by stonecrusher** [comment]
Unfortunately I cannot see a "share" item anymore. Maybe only if you're logged in?
![share](https://user-images.githubusercontent.com/1388389/135727548-d3a7a90b-df93-4b05-b83c-c8bd386c8a42.png)

Send Tab To Device is still in the source code (`#context_sendTabToDevice`), but hidden for me. The selector seems unchanged.
Not sure what they changed. I'm also on FF 92.0.1

**Comment by stonecrusher** [comment]
Still can't see "share" with a fresh profile, but can see it in another one. Fixed.
No news about `#sendTabToDevice`. Please open a new issue if necessary.
https://github.com/stonecrusher/simpleMenuWizard/commit/424b6e483d6f00018714d3ca67ec1dc0de54bdde
