### ISSUE TITLE
text-link-context.css

### ISSUE THREAD

**Issue by wvxwxvw** [stonecrusher/simpleMenuWizard#57]
Test

		https://github.com/stonecrusher/simpleMenuWizard/issues/new
  
#context-openlinkincurrent

**Comment by stonecrusher** [comment]
Ah wow, a hidden treasure :-)

I was tempted putting it into link-context, but actually it belongs to select-context.

Thank you. [Fixed.](https://github.com/stonecrusher/simpleMenuWizard/commit/8d99e62b87b5e0dfdf7a741a5f10c5f5b8b871fc)

**Comment by stonecrusher** [comment]
Haha well... happy little mistakes
https://github.com/stonecrusher/simpleMenuWizard/commit/0e76da59e0f441238c57d788d47c2c5d3bafb771
