### ISSUE TITLE
TabsToolbar Options ?

### ISSUE THREAD

**Issue by GitCurious** [stonecrusher/simpleMenuWizard#58]
First off, thanks for this - I've only just found it !

My question is, I can't find the options to change folders and items contained inside folders on the Bookmarks toolbar, 
am I going blind or don't they exist for some reason ?

Thanks.

**Comment by stonecrusher** [comment]
Hi!  
No you're not blind, it's currently not contained. I personally do not use the bookmarks toolbar, so I must have overlooked it.
I'll probably add it soon and leave this open.

I hope you meant the bookmarks toolbar? I don't know about folders in the tabs bar. Maybe add a screenshot if you didn't mean the bookmarks toolbar.

**Comment by GitCurious** [comment]
Thanks.
I **did** mean the bookmarks toolbar - my head was spinning earlier, didn`t even notice I said Tabs !
