### ISSUE TITLE
Drop down menus bug

### ISSUE THREAD

**Issue by a-rock-lobster** [stonecrusher/simpleMenuWizard#65]
Hullo,

Recently I have found that certain drop down menus are not opening. I think this is mostly at online checkouts, in particular when opening lists of countries. 

I think that, by trial and error, I have traced the issue back to simpleMenuWizard. The problem goes away when I delete the SMW files. I have tried removing my custom CSS, but this isn't the issue. 

I'm still in the process of narrowing down the cause. Perhaps someone can see if they can replicate the issue. 

Cheers,

**Comment by stonecrusher** [comment]
Hi!
I'm not sure what you stumbled upon.
SMW shouldn't interact with website content at all (we use userChrome.css not userContent.css). But dropdowns might be treated as belonging to the browser.
So in theory it's possible if a selector is too broad.

What is really strange is that the problem is still there with custom CSS removed (=fresh copy of SMW).

SMW shouldn't target anything at all by default (except `#leave_this_dummy_here`).

If you have a public example I can help to investigate/replicate.

Greets

**Comment by a-rock-lobster** [comment]
I haven't come across a convinient example yet. Mostly in checkouts behind alot of other information one has to fill out. I think in some cases it is related to a particular payment service a lot of merchants use. 
As soon as a find a good example which isn't a pain to get to I'll post a link.

**Comment by a-rock-lobster** [comment]
So, I have found a relatively easy example and the culprit line. 
Example: trying to select country from dropdown menu (note, you may need to opt to purchase through website rather than redirect to apple store).
Link: https://hazeover.com/buynow.html?nomas

Culprit line of CSS:
#mainPopupSet menuitem[disabled="true"] { display: none !important; }
This line is to "Hide all inactive menu items".

This line is found in the Chrome.css file (which I have renamed as I have another chrome.css file).

After deleting/commenting out that line the problem went away. 

Not sure if this is a problem with fresh installs or it is combining with some other changes I have made.

**Comment by stonecrusher** [comment]
That was helpful, I can reproduce!

And hopefully could fix it:  
As supposed, that language dropdown is displayed as firefox-internal item, thus receives the `menuitem` under `#mainPopupSet` which is not visible in the HTML source.

I hope to still target all FF-internal disabled items while reducing the risk of targeting something like a country list dropdown in the wild with this more specific CSS selector:
`#mainPopupSet menuitem[disabled="true"][id][data-l10n-id] { display: none !important; }`

It would be nice if you'd be my beta-tester and use this for a while. If it works well, I'll apply it to the project.

BTW that option is disabled by default (just like all others), so it only affects people that wanted to hide disabled items.

**Comment by a-rock-lobster** [comment]
Great!

Sure I can test it. 

I just replace the problem line with 
 #mainPopupSet menuitem[disabled="true"][id][data-l10n-id] { display: none !important; }
correct?

**Comment by stonecrusher** [comment]
yes, exactly. Thanks again!

**Comment by a-rock-lobster** [comment]
Okay. Will do.

**Comment by stonecrusher** [comment]
I guess it works fine? Time to merge changes.

**Comment by a-rock-lobster** [comment]
Hi, yes it's been working fine :) Sorry, I forgot to report back.
