### ISSUE TITLE
Taking entries out of sub-menus

### ISSUE THREAD

**Issue by eunomicZenith** [stonecrusher/simpleMenuWizard#68]
Hello! I would like to take things like "Move to New Window" and "Close Tabs to the Left/Right" out of their sub-menus and into the main tab context menu. That doesn't seem to be possible, currently - if I disable the sub-menu by editing the tab-content.css file, the entire sub-menu disappears, including its contents, which isn't what I want to do.

Is what I want feasible? If yes, how could I do it? Perhaps you could also add support for it?

**Comment by stonecrusher** [comment]
Unfortunately I cannot make structural changes with CSS. That would be possible with JavaScript, but is out of scope of this project. You'd first need a way to load UserChrome.js scripts. That was easy before Firefox 57 and is now harder to achieve.

There are different approaches. I know it works, but the [source I have](https://github.com/Endor8/userChrome.js) is written in german. I think this will help you:
https://github.com/Endor8/userChrome.js
Still you need to know how to code JavaScript.

CSS actually is for styling, but also can hide items and under certail circumstances can change the order of items that are on the same level.
