### ISSUE TITLE
Feature request - add contextmenu of Container Tabs

### ISSUE THREAD

**Issue by Tiagoquix** [stonecrusher/simpleMenuWizard#69]
Right-click in the "+" button to open a new tab shows up these options when Container Tabs are enabled:

![image](https://user-images.githubusercontent.com/30274161/196860082-af2ad51e-f523-4b0c-90a1-885fcbca2a20.png)

To be able to see them, enable Container Tabs in `about:config` by setting both `privacy.userContext.enabled` and `privacy.userContext.ui.enabled` to `true`.

**Comment by stonecrusher** [comment]
Thank you.
I added it: https://github.com/stonecrusher/simpleMenuWizard/commit/7c1128efdde7e83668115391df660f0940e484fe
