### ISSUE TITLE
Feature request: remove new "Extensions" button (FF109)

### ISSUE THREAD

**Issue by Tiagoquix** [stonecrusher/simpleMenuWizard#71]
![image](https://user-images.githubusercontent.com/30274161/213021460-19ccb00e-12cc-4df2-a060-0e72c9b98e61.png)
Top right corner.

https://support.mozilla.org/en-US/kb/unified-extensions

**Comment by stonecrusher** [comment]
Just right click it and then remove?!

**Comment by stonecrusher** [comment]
Ah ok, I didn't get the 109 update yet. And already have that button up there. Thanks, I'll have a look at it.

**Comment by stonecrusher** [comment]
https://github.com/stonecrusher/simpleMenuWizard/commit/1cb77767588bf67a5cf8825141dfcd6d7fd86369

**Comment by stonecrusher** [comment]
Also note that you can restore the old behaviour by setting
`extensions.unifiedExtensions.enabled`
in `about:config` to `false`

**Comment by stonecrusher** [comment]
yeah the identifier is `#nav-bar-overflow-button`.
But actually this should have the same result as

`extensions.unifiedExtensions.enabled` `true` and  `#unified-extensions-button` hidden?

So you don't need to restore old behaviour.
