### ISSUE TITLE
Tab-context.css and Tree Style Tab addon

### ISSUE THREAD

**Issue by maestropss** [stonecrusher/simpleMenuWizard#72]
Hello. Removing elements from the tab context menu has no effect on the tabs menu if TST add-on is used. Looks like TST has a different name of the tab variable (not a default one, i.e. #tabContextMenu). How can this issue be solved? Thanks (ESR 102)

**Comment by stonecrusher** [comment]
Hi!
That is because that menu is part of the addon. The addon mimics the original menu.
But it looks like the author adopted the naming of the IDs and just prefixed with `treestyletab_piro_sakura_ne_jp-menuitem-_context_`

So try `#treestyletab_piro_sakura_ne_jp-menuitem-_context_tabContextMenuExampleEntry` 
 instead of `#tabContextMenuExampleEntry`.

**Comment by maestropss** [comment]
Thank you for your reply. I have tried to add the following strings. But there is no effect. 
#treestyletab_piro_sakura_ne_jp-menuitem-_context_tabContextMenu #context_openANewTab, 
#treestyletab_piro_sakura_ne_jp-menuitem-_context_tabContextMenu #context_reloadTab,

I have also tried to look at the code of  SingleFile addon as it adds a sub menu to the tab menu context. I hoped that I would find a TST tab naming. But I can not see how they do it.

**Comment by stonecrusher** [comment]
No, I mean like this:

    #treestyletab_piro_sakura_ne_jp-menuitem-_context_openANewTab,
    #treestyletab_piro_sakura_ne_jp-menuitem-_context_reloadTab,

And you don't need `#tabContextMenu`

**Comment by maestropss** [comment]
Thanks. Most of the items are removed. Some are still there though. Such as New tab, move tabs. I suppose that this is because of the add-on tree structure of the tabs. Therefore the naming may be different. Anyway, it is much better now.

**Comment by stonecrusher** [comment]
This might be helpful to you:
https://i.imgur.com/Ey9slWQ.png
https://i.imgur.com/OHJvoQC.png
