### ISSUE TITLE
Firefox crashing when opening, inconsistent behavior

### ISSUE THREAD

**Issue by firefoxlover** [stonecrusher/simpleMenuWizard#73]
as far as I understood, by default everything is deactivated?

So what I did is rename css files where I didnt want any change, so they cant be imported.

And for things I want, I remove the "#"

Now I set the use of the CSS in the about:config and Firefox crashes on startup

Edit: ok so the CSS deactivates elements instead of showing them? I am confused, Example:

```
blank-context.css

context-nagivation (and all other elements) are disabled with "#" and are shown!

context-savepage is enabled without a bookmark and shown

````

```
opt_noSendToDevice.css

doesnt seem to change anything, I get this "email image" if I activate or deactiate entries....

```

**Comment by stonecrusher** [comment]
Please read the instructions carefully.

- Renaming .css files doesn't make sense as the system will search for them and not find them. It's a performance decrease. But you won't recognize the difference anyway, as it will be a few microseconds. If you want to optimize that nontheless, you may remove the corresponding `@import` line from the `userChrome.css`.
- Do not remove any `#`.  
  - **Remove menu item:** Remove `/*` at the beginning of the line.
  - **Leave menu item:** Add `/*` to the beginning of the line (by default every option is deactivated).

**Comment by firefoxlover** [comment]
Thank you, new to CSS, used to Python e.g. where the "#" determines active / inactive.

Thanks for this great script! Maybe leave this issue open for other people

**Comment by stonecrusher** [comment]
No problem, you're welcome.

Other people can also find and comment it when it's closed. No further action needed here.
