### ISSUE TITLE
Bookmark contexts not available

### ISSUE THREAD

**Issue by firefoxlover** [stonecrusher/simpleMenuWizard#74]
Hi, great project!

Only missing is the Bookmarks contexts. I tried finding out its CSS name, but unsure

maybe its #bookmarks-menu ?

**Comment by stonecrusher** [comment]
Hey, thanks :)
Just had the same problem as everyone else coming here and decided to make a complete list of selectors.

Did you have a look at the `sidebar-context.css`? Or maybe give me a screenshot of what exactly you mean?
Have a good week!

**Comment by firefoxlover** [comment]
sorry must have overseen it.
