### ISSUE TITLE
[Feature request] Hide "Open in New Container Tab" when right-clicking in bookmarks

### ISSUE THREAD

**Issue by Tiagoquix** [stonecrusher/simpleMenuWizard#76]
![image](https://github.com/stonecrusher/simpleMenuWizard/assets/30274161/a5c96a8e-488f-4949-a65e-32c04436fa27)

**Comment by stonecrusher** [comment]
Gave the whole file an update. https://github.com/stonecrusher/simpleMenuWizard/commit/e6f92ae433b9df9b67e9a8870246939db9b5af43
