### ISSUE TITLE
Firefox 115 Help- New Device

### ISSUE THREAD

**Issue by freonheat** [stonecrusher/simpleMenuWizard#77]
Under the main menubar help menu, you don't have an entry for the new "Switching to a New Device" menu entry defined yet.

Update:  Also not present for hamburger menu's help either

**Comment by stonecrusher** [comment]
Thank you for the hint.
Fixed https://github.com/stonecrusher/simpleMenuWizard/commit/b985afc94a6c0024c2009b83e7eb1dd89fa14355

**Comment by freonheat** [comment]
Great/thanks!
