### ISSUE TITLE
Bookmarks toolbar, open all bookmarks

### ISSUE THREAD

**Issue by freonheat** [stonecrusher/simpleMenuWizard#78]
Is there a way to remove "Open All Bookmarks" from the bookmark toolbar's context (right click) menu?

Thanks :)

**Comment by stonecrusher** [comment]
Yes, have a look at [sidebar-context.css](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/sidebar-context.css)

**Comment by freonheat** [comment]
> Yes, have a look at [sidebar-context.css](https://github.com/stonecrusher/simpleMenuWizard/blob/master/simpleMenuWizard/sidebar-context.css)

OMG, I guess my searching skills need some improvement.  Thanks!
