### ISSUE TITLE
Is there a place that the elipses context menu can be controlled?

### ISSUE THREAD

**Issue by jacebenson** [stonecrusher/simpleMenuWizard#8]
I think that's what it is called.
Screenshot provided for clarity;

![image](https://user-images.githubusercontent.com/638764/37266385-d0b94eea-2587-11e8-8134-63d5a2f8f6f9.png)

**Comment by jacebenson** [comment]
I started poking around.  Looks like they are called the following, but I'm still not sure this will make the difference..
```
/* pageAction-panel-bookmark                            /* Bookmark This Page  */
/* pageAction-panel-pocket                              /* Save Page to Pocket */
/* pageAction-panel-bookmarkSeparator                   /* Separator           */
/* pageAction-panel-copyURL                             /* Copy Link           */
/* pageAction-panel-emailLink                           /* Email Link...       */
/* pageAction-panel-sendToDevice                        /* Send Tab to Device  */
/* pageAction-panel-screeenshots                        /* Take a Screenshot   */
```

**Comment by jacebenson** [comment]
I found where it's controlled.  I made a PR to add this to your repo.

**Comment by stonecrusher** [comment]
Thanks for your report and PR, I merged it into the project.
I never used that menu by myself, so I overlooked it.
In my FF60 with default prefs I can't see the three dots at all, maybe Mozilla removed them?
