### ISSUE TITLE
add selector to remove 'Search with Google in a Private Window'

### ISSUE THREAD

**Issue by atomGit** [stonecrusher/simpleMenuWizard#82]
apparently i forgot how to find the css selectors for context menus and i find this one is particularly annoying 'Search with Google in a Private Window'

ff v119 - maybe they just added it because i haven't seen this menu item before

**Comment by stonecrusher** [comment]
I can't reproduce it. Try to use troubleshoot mode (restarts FF with addons temporarly disabled). It can be found at `about:support`.

If that context entry is gone, then it comes from an addon.

**Comment by atomGit** [comment]
ha, saw these earlier today and promptly forgot about them...

```
browser.search.separatePrivateDefault (def=true)
browser.search.separatePrivateDefault.ui.enabled (def=false)
```

setting the 2nd one to true will reveal the menu item -  you may want to ignore my request since it defaults to false

**Comment by stonecrusher** [comment]
Never heard about that option.
Good to know.
I'm glad it's solved 👍
