### ISSUE TITLE
question regarding the use of 'menuitem'

### ISSUE THREAD

**Issue by atomGit** [stonecrusher/simpleMenuWizard#83]
in a similar project, all of the css selectors are prefixed with 'menuitem' (except for 2 which are prefixed with 'menu')...

`menuitem#context_reloadTab`

i'm just curious as to why that is - is it better practice to do this? i noticed though that some items won't work with this prefix

**Comment by stonecrusher** [comment]
Well, `#` is a selector for an ID and IDs should by definition be unique. CSS doesn't enforce uniqueness, so it can be more secure to narrow it down more by adding `menuitem`.

However, the more specific you are, the more brittle it is against change. So I only directly used the more concise ID selector, which is sufficient.

By the way, `menuitem` is a non-standard html element which never made it out of the "draft" status.

Almost all html elements can have an ID. Depending on your workflow it can be helpful to also specify the type of element you are targeting, so you won't confuse the CSS properties allowed.

**Comment by atomGit** [comment]
> menuitem is a non-standard html element ...

i see - thanks for the info :)
