### ISSUE TITLE
Send Tab to Device + Tree Style Tabs not hiding

### ISSUE THREAD

**Issue by ktz373** [stonecrusher/simpleMenuWizard#86]
Send Tab to Device button appears when right clicking a tab inside Tree Style Tabs, even when disabled inside simpleMenuWizard. Is there any way to disable it when right clicking a tab inside Tree Style Tabs?

**Comment by ktz373** [comment]
Solved.

Add 

`#treestyletab_piro_sakura_ne_jp-menuitem-_context_sendTabsToDevice,`

**Comment by stonecrusher** [comment]
yes it's purely from the addon, so I won't add it. But good to have it documented here for the googlers
