### ISSUE TITLE
[Feature request] Add option to remove "add search engine" in urlbar-context.

### ISSUE THREAD

**Issue by IAMNOTRANA** [stonecrusher/simpleMenuWizard#88]
![1](https://github.com/stonecrusher/simpleMenuWizard/assets/63802687/ecf67e1d-da32-452f-91bd-24359a867d82)

I'm not sure if it is even possible to remove this, but I couldn't find such an option in about:config (or maybe I just failed to find one).

**Comment by stonecrusher** [comment]
Strangely, I already got the separator, but not the "Add" entries.

I added it in https://github.com/stonecrusher/simpleMenuWizard/commit/bd2cb3285f9775a84d47d4799d10ce22bf089fe0

I hope it works for you.

**Comment by IAMNOTRANA** [comment]
> [](https://github.com/stonecrusher/simpleMenuWizard/commit/bd2cb3285f9775a84d47d4799d10ce22bf089fe0)
> 
> I hope it works for you.

Yep, that worked. Thank you.

**Comment by IAMNOTRANA** [comment]
> Strangely, I already got the separator, but not the "Add" entries.
> 
> I added it in [bd2cb32](https://github.com/stonecrusher/simpleMenuWizard/commit/bd2cb3285f9775a84d47d4799d10ce22bf089fe0)
> 
> I hope it works for you.

Yep, that worked. Thank you.
