### ISSUE TITLE
MacBookPro M1 Firefox dont respect this custom css

### ISSUE THREAD

**Issue by root-host** [stonecrusher/simpleMenuWizard#90]
hello, thanks for this wizard, I put CSS in the Chrome folder but the firefox doesn't respect it nothing changes if I put in my work laptop that is running Win11 Pro everything works fine, any ideas?

**Comment by stonecrusher** [comment]
Yes, did you read the important notes?

If you're running macOS and Firefox 89+, make sure you set widget.macos.native-context-menus to false otherwise it won't work.

**Comment by root-host** [comment]
> Yes, did you read the important notes?
> 
> If you're running macOS and Firefox 89+, make sure you set widget.macos.native-context-menus to false otherwise it won't work.

Yes im i set widget.macos.native to false and still after restart firefox it dont work,maybe firefox for m1 is bot the same as for intel?

**Comment by stonecrusher** [comment]
Sorry I have no idea and no mac to try and test stuff.
